#! /bin/bash
# script para compilar el programa y ejecutarlo
# ejecutar ./dijkstra -h para ver las opciones disponibles

cd dijkstra-heap/src
rm *.class
javac -cp ../commons-cli-1.4/commons-cli-1.4.jar *
java -cp :../commons-cli-1.4/commons-cli-1.4.jar Dijkstra $@ 